version: '3.8'

services:
  #  docker-compose up
  jenkins:
    image: jenkins/jenkins:latest
    container_name: "jenkins"
    labels:
      kompose.service.type: nodeport
    ports:
      - '8080:8080'
    volumes:
      - /srv/data/jenkins_data:/jenkins_home
      - /srv/data/jenkins:/var/jenkins_config
#  create postgresql database
  postgresql_database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=snjAdmin
      - POSTGRES_PASSWORD=snjAdmin1234
      - POSTGRES_DB=snjdb
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    ports:
      - '5050:80'
    restart: always
    volumes:
      - pgadmin:/root/.pgadmin
volumes:
  database-data:
  pgadmin:
  jenkins_data:
    driver: local
  jenkins:
    driver: local